### ISSUE TITLE
[Feature Request] Apply lighter boats to all boats

### ISSUE THREAD

**Issue by Zygus42** [CplPibald/PiTweaks#10]
Would be great if the fix to make boats lighter applied to all items of type boat so that it affected boats added by mods, such as Biomes O Plenty for example.

**Comment by CplPibald** [comment]
I like this idea, but it probably won't be done.  I'm not working in 1.12 anymore, and the boats tweak didn't come forward into 1.15/1.16 - partly because the vanilla boat code was notoriously difficult to patch.

If I ever bring back a boat tweak, I'll make sure it applies to mod boats too.
