### ISSUE TITLE
2x2 Recipes not working

### ISSUE THREAD

**Issue by supersaiyansubtlety** [CplPibald/PiTweaks#12]
The 2x2 recipe options are not working for me. No recipes I've tested have their 2x2 versions, it seems like no change took place. 
The logs below are from a freshly made world with no other mods installed.

Minecraft: 1.12.2
Forge: 1.12.2 - 14.23.5.2847
PiTweaks: PiTweaks-1.12-1.1.1

[latest.log](https://pastebin.com/tkkhyBB4)
[debug.log 1/2](https://pastebin.com/zCiRD4nR)
[debug.log 2/2](https://pastebin.com/X8nzgF6z)

**Comment by CplPibald** [comment]
2x2 recipes were always buggy, which is why they're disabled by default in the config (you did turn them on, right?).

I'm not working on 1.12 anymore, and for 1.14+, the stonecutter is a better option for making most slabs/stairs.
