### ISSUE TITLE
[1.12.2 Feature/Compatibility Request] Anvil Penalty for Enchant Only

### ISSUE THREAD

**Issue by Ameranth** [CplPibald/PiTweaks#14]
Hello and thank you for your work!

I hope you would find interest in expanding your anvil patch to config for removing only anvil _repair_ cost growth--so that the work penalty remains for anvil _enchanting_.

Yours seems to be the only anvil patch compatible with [Enchantment Control](https://www.curseforge.com/minecraft/mc-mods/enchantments-control), so having this extra config would help a lot for packs trying to significantly alter enchants.

**Comment by CplPibald** [comment]
Minecraft uses one NBT tag (`RepairCost`) attached to an item for both operations.  PiTweaks sets that value to zero whenever you take a stack from an anvil.  It also overrides book handling, but repairs use the vanilla code.  

I can think of two ways to do this.  The first method to do that would be to override vanilla code for item repairs in the same way as book enchants.  The second would be to track cumulative enchant cost in a separate variable and apply it during book enchants.  Both would complicate the code quite a bit, and it's not clear how many people would want this feature.

Either way, you are welcome to fork the mod and make the changes. I can describe what needs to change in more detail if you like.  I am not really working on 1.12 anymore, so I don't see this getting a lot of priority right now.

**Comment by Ameranth** [comment]
Thank you for the detailed response, I completely understand that it isn't something you'll get to.

I am not yet familiar enough with minecraft modding to tackle this myself, but I'll keep in mind your kind offer to explain if I get into it in the future.

Thank you again for your time
