### ISSUE TITLE
[1.12.2] Unbreaking is bugged

### ISSUE THREAD

**Issue by Silencx** [CplPibald/PiTweaks#16]
The enchanted book unbreaking V and up are not craftable. Its is possible to do it on a item but not as a book after getting unbreaking 5 on 2 tools and trying to combine them its returns to unbreaking III

**Comment by DoomRater** [comment]
This bug report seems to be incorrect.  It is combination of enchantments on items only that seems to be inconsistent with book enchantment uncapping.  I can reproduce with any enchantment on an item while trying to combine two enchanted items with multiple different enchantments- the enchantments will always be max vanilla level in the output.
