### ISSUE TITLE
Enabling 2x2 stairs causes server crash 1.12.2

### ISSUE THREAD

**Issue by PurpleHel** [CplPibald/PiTweaks#2]
Setting stairs to false in config fixes it. Wasn't really using the 2x2 recipe anyway, so don't care enough to figure out if it's just PiTweaks or if it's an interaction with another mod, but sharing the crash report is pretty painless, so here you go.

https://pastebin.com/s9yggxus

Unrelated, searching PiTweaks on curseforge doesn't turn up your mod, which is minorly inconvenient. :)

**Comment by CplPibald** [comment]
Looks like there's a mod adding a recipe that's returning an empty list for `getMatchingStacks()`, and that's making the stair scanning code blow up.

Thanks for bringing this to my attention.

**Comment by PurpleHel** [comment]
My full mods list in a slightly more readable form than the crash report list can be found at https://pastebin.com/yaz3V5rT

I'm willing to do some minor testing of the 'hey, disable such-and-such mod and see if it still crashes?' sort. Just not up to trying to hunt down for myself if it was mod interaction or internal. :)

**Comment by CplPibald** [comment]
I don't think it matters which mod it's interacting with.  As long as Forge allows it, some mod will mess it up.  PiTweaks needs to be smarter about ignoring malformed recipes when scanning.

Can you check if you still see the same crash with this version?  If that fixes it, I'll upload it to curseforge.  Thanks.

https://www.dropbox.com/s/sa0r5rqnsjlf636/PiTweaks-1.12-0.5.1.jar?dl=1

**Comment by PurpleHel** [comment]
Checking! :)

**Comment by CplPibald** [comment]
You said this is on a server?  Did you also update your client config to turn the tweak back on?

I noticed in my own testing the recipe works as long as the 2x2 tweak is enabled on the server, but for it to show up in JEI, the tweak has to also be enabled on the client.

**Comment by PurpleHel** [comment]
Ah, ok, cool. I did not update the client config, so that'd be the problem with it not showing up in JEI. :)
