### ISSUE TITLE
Fast Furnace not working (mod conflict)

### ISSUE THREAD

**Issue by beanaboston** [CplPibald/PiTweaks#5]
One of the mods in my custom modpack is conflict with your mod and making it so the furnace doesn't speed up. I don't have time to go through myself and narrow down what mod right now, but will hopefully do that soon. Just letting you know. My mod list is here: https://paste.dimdev.org/mivavaxifo.md

**Comment by CplPibald** [comment]
I'm afraid I can't do anything with this report unless you can narrow it down to which mod is conflicting.  Fast Furnaces replaces the vanilla furnace TileEntity when you place a furnace block.  It will therefore will conflict with any other mod that changes that TileEntity.

Other possibilities to check:
- Check your config and make sure that fast furnaces are turned on.  (It's off by default in 0.x versions)
- Try breaking the furnace block and re-placing it.  That forces the tile entity update.
