### ISSUE TITLE
Incompatibility with AppleCore

### ISSUE THREAD

**Issue by squeek502** [CplPibald/PiTweaks#6]
CplPibald's Tweaks overrides FoodStats, which is incompatible with AppleCore (and any mod that also overrides FoodStats).

Two options to solve this:
- Use the same method suggested [here](https://github.com/TheRandomLabs/RandomTweaks/issues/18) when AppleCore is installed
- Don't override FoodStats when the config options for that feature are turned off (only a half-fix, as users would have to disable that feature in order to 'solve' the incompatibility).

See also https://github.com/squeek502/AppleCore/issues/134

**Comment by CplPibald** [comment]
PiTweaks should not override FoodStats when both food tweaks are turned off.  See [onEntityJoinWorld here](https://github.com/CplPibald/PiTweaks/blob/master/src/main/java/us/bemrose/mc/pitweaks/FoodCapTweak.java#L19).  For AppleCore compatibility,  make sure to disable both uncapFood and uncapSaturation tweaks in config/pitweaks.cfg and then restart Minecraft.

If you are certain the tweaks are disabled and are still seeing this problem, let me know and I will download AppleCore to investigate.

**Comment by squeek502** [comment]
Ah, alright, didn't check that. I'm the author of AppleCore, just reporting what was said in https://github.com/squeek502/AppleCore/issues/134: 

> I had hoped turning both configs off dealing with Food for CplPibald would fix the issue, however, this doesn't seem to be the case.

From your source code, it seems like that can't be true, though.

**Comment by CplPibald** [comment]
Detecting AppleCore and using its APIs per the thread you linked looks like definitely the cleanest way to handle this.

**Comment by squeek502** [comment]
See https://github.com/TheRandomLabs/RandomTweaks/commit/0489814bc8b4c84925c27dd81610f2ae6965571e for a more complete example implementation

**Comment by CplPibald** [comment]
Issued a hotfix (v1.1.1) to work around the crashes by detecting AppleCore and disabling the conflicting code.  Since this feature was completely new in PiTweaks, disabling it will not affect anybody who uses both PiTweaks and AppleCore in a modpack.

Leaving this open for now, as I need to think some more about how I want to approach mod compat issues like this.
