### ISSUE TITLE
Not really an issue but please add

### ISSUE THREAD

**Issue by futurenp** [CplPibald/PiTweaks#7]
I need a mod that can add ONLY protection stacking (for example protection 4 and fire protection 4 on the same chest plate) and smite, sharpness and bane of arthropods stacking on weapons sort of like 1.14

I am working on a modpack and I don't know a ton about making mods so if you do help that would be amazing!

**Comment by CplPibald** [comment]
Stale issue.  If you still need this, I can show you where to tweak my anvil code to get what you want here.  (The function is called `canApplyEnchant`)
